name: Copy Protos to Kuberex API

on:
  push:
    branches:
      - main
    # paths:
    #   - 'proto/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# permissions:
#   contents: write  # Allows writing to the repository (for pushing changes)

permissions: {}


jobs:
  copy-protos-to-kuberex-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository 'user-service'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: source_repo
          fetch-depth: 0

      - name: Checkout target repository 'kuberex-api'
        uses: actions/checkout@v4
        with:
          repository: hitham07/target
          token: ${{ secrets.test }}
          path: target_repo
        env:
          GITHUB_TOKEN: ${{ secrets.test }}

      - name: Copy directory
        run: |
          # # clean up the target directory
          # rm -rf target_repo/api-proto/proto/services/pki_service
          # mkdir -p target_repo/api-proto/proto/services/pki_service
          # # redirect stderr to /dev/null to avoid error message because the common directory is empty
          # cp -Rf source_repo/proto/common/* target_repo/api-proto/proto/common 2> /dev/null || true
          # cp -Rf source_repo/proto/services/* target_repo/api-proto/proto/services/pki_service/


          mkdir -p target_repo/proto/common


          git -C source_repo  diff --name-status HEAD~1 | grep -E '^[D]' | awk '{print $2}' | awk -F'common/|/v1' '{print $2}' | sort | uniq | xargs -I {} echo "target_repo/api-proto/proto/common/{}"

          git -C source_repo diff --name-status HEAD~1 | grep -E '^[D]' | awk '{print $2}' | awk -F'common/|/v1' '{print $2}' | sort | uniq | xargs -I {} rm -rf "target_repo/api-proto/proto/common/{}"

          cp -Rf source_repo/proto/common/* target_repo/api-proto/proto/common 2> /dev/null || true


      - name: Commit and push changes
        run: |
          cd target_repo
          git config user.name "${{ github.actor }}"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "update api protos of user-service"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.test }}
