name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the project..."
          # Your build command here
          # Simulate success or failure
          exit 1  # Uncomment to simulate failure for testing

      - name: Print Status
        run: |
          if [ $? -eq 0 ]; then
            echo "Pipeline Status: SUCCESS"
          else
            echo "Pipeline Status: FAILURE"
          fi
