name: Repository Dispatch Example

on:
  repository_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Received a custom dispatch event!"

      - name: Print Client Payload
        run: |
          echo "Client Payload:"
          echo "${{ toJson(github.event.client_payload) }}"

