name: Repository Dispatch Example

on:
  repository_dispatch:
    types: [custom_event]

  

# concurrency:
#   group: sequential-workflow
#   cancel-in-progress: false


jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: build the image 
        run: |
          echo "Pushing protos to github"
          sleep 5
          echo "Done waiting"
          echo "Pushing protos to github"

  run:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo message
        run: echo "Received a custom dispatch event!"

      - name: Print Client Payload
        run: |
          echo "Client Payload:"
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Push protos to github
        run: |
          echo "Pushing protos to github"
          sleep 10
          echo "Done waiting"
          echo "Pushing protos to github"

   
      - name: Execute if the job was cancelled
        if: ${{ cancelled() }}
        run: echo "Job status is $111111111111111111"
      

